# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(598, 395)
        Form.setStyleSheet("#Form{\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.baslat_button = QtWidgets.QPushButton(Form)
        self.baslat_button.setGeometry(QtCore.QRect(50, 240, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.baslat_button.setFont(font)
        self.baslat_button.setObjectName("baslat_button")
        self.dayandir_button = QtWidgets.QPushButton(Form)
        self.dayandir_button.setGeometry(QtCore.QRect(220, 240, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.dayandir_button.setFont(font)
        self.dayandir_button.setObjectName("dayandir_button")
        self.main_vaxt = QtWidgets.QLabel(Form)
        self.main_vaxt.setGeometry(QtCore.QRect(180, 80, 241, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(34)
        self.main_vaxt.setFont(font)
        self.main_vaxt.setStyleSheet("color: rgb(255, 255, 255);")
        self.main_vaxt.setObjectName("main_vaxt")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(160, 90, 271, 81))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.sifirla_button = QtWidgets.QPushButton(Form)
        self.sifirla_button.setGeometry(QtCore.QRect(390, 240, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.sifirla_button.setFont(font)
        self.sifirla_button.setObjectName("dayandir_button_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.baslat_button.setText(_translate("Form", "Başlat"))
        self.dayandir_button.setText(_translate("Form", "Dayandır"))
        self.main_vaxt.setText(_translate("Form", "00:00:00"))
        self.sifirla_button.setText(_translate("Form", "Sıfırla"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
